In [1]:
import pandas as pd
import numpy as np 
import matplotlib .pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as sm

In [2]:
import os
os.chdir('E:\M_L_N\ML\MachineLearning-master\Datasets')
data=pd.read_csv('50_Startups.csv')

In [3]:
data.shape

(50, 5)

In [4]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
feature_set=data.iloc[:,0:4].values
labels_set=data.iloc[:,4].values

## Convert Text data in form of numeric y using encoder 

In [6]:
le=LabelEncoder()
feature_set[:,3]=le.fit_transform(feature_set[:,3])

In [7]:
feature_set

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [9]:
feature_set[:,1:]

array([[136897.8, 471784.1, 2],
       [151377.59, 443898.53, 0],
       [101145.55, 407934.54, 1],
       [118671.85, 383199.62, 2],
       [91391.77, 366168.42, 1],
       [99814.71, 362861.36, 2],
       [147198.87, 127716.82, 0],
       [145530.06, 323876.68, 1],
       [148718.95, 311613.29, 2],
       [108679.17, 304981.62, 0],
       [110594.11, 229160.95, 1],
       [91790.61, 249744.55, 0],
       [127320.38, 249839.44, 1],
       [135495.07, 252664.93, 0],
       [156547.42, 256512.92, 1],
       [122616.84, 261776.23, 2],
       [121597.55, 264346.06, 0],
       [145077.58, 282574.31, 2],
       [114175.79, 294919.57, 1],
       [153514.11, 0.0, 2],
       [113867.3, 298664.47, 0],
       [153773.43, 299737.29, 2],
       [122782.75, 303319.26, 1],
       [105751.03, 304768.73, 1],
       [99281.34, 140574.81, 2],
       [139553.16, 137962.62, 0],
       [144135.98, 134050.07, 1],
       [127864.55, 353183.81, 2],
       [182645.56, 118148.2, 1],
       [153032.06, 107138.38

### Split data in trian ans test part for training and testing

In [10]:
train_feature,test_feature,train_labels,test_labels=train_test_split(feature_set,labels_set,test_size=.2,random_state=0)

In [11]:
model=LinearRegression()
model.fit(train_feature,train_labels)

LinearRegression()

In [12]:
pedict_labels=model.predict(test_feature)

In [13]:
test_labels[0]

103282.38

In [14]:
pedict_labels[0]

103959.40508021144

In [15]:
test_labels

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [16]:
pedict_labels

array([103959.40508021, 132398.73236694, 133529.03790148,  72958.28368314,
       179534.78737166, 115533.62584099,  67476.95847883,  98504.36199396,
       114789.16083781, 168972.21909945])

In [17]:
model.coef_

array([7.77203690e-01, 3.02432445e-02, 3.49236072e-02, 3.15877202e+02])

In [18]:
model.intercept_

42658.087123248944